version: '3'
services:
  mongo: # db non relazionale
    image: mongo
    restart: always # viene utilizzato nei server: nel caso si bloccasse  il server riparte.
    volumes: # crea un volume di memoria persistente anche al conteiner 
      -  localdatabase:/data/db
    networks:
      -  composenetwork
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      -  8081:8081
    environment:
      -  ME_CONFIG_MONGODB_SERVER=mongo
      -  ME_CONFIG_MONGODB_PORT=27017
    networks:
      -  composenetwork
    depends_on:
      -  mongo
      
volumes:
  localdatabase:

networks:
  composenetwork:
    driver: bridge